In [1]:
import pandas as pd
from sqlalchemy import create_engine
from datetime import date, timedelta
from config import key

# Extracting DATA
The data I gathered camed from https://www.kaggle.com/danield2255/data-on-songs-from-billboard-19992019 where it gave me a couple of CSV files to work with.

In [2]:
#the intiial data set
csv_file = "Resources/billboardHot100_1999-2019.csv"
billboard_data_df = pd.read_csv(csv_file)
billboard_data_df

,Unnamed: 0,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Date,Genre,Writing.Credits,Lyrics,Features
0,1,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr...","Jozzy, Atticus ross, Trent reznor, Billy ray c...","Old Town Road Remix \nOh, oh-oh\nOh\nYeah, I'm...",Billy Ray Cyrus
1,2,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,NaN,2019-07-06,"June 21, 2019",Pop,"Cashmere cat, Jack patterson, Charli xcx, Benn...",Senorita \nI love it when you call me senorita...,NaN
2,3,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ...","Billie eilish, Finneas","bad guy \nWhite shirt now red, my bloody nose\...",NaN
3,4,Khalid,Talk,4,3.0,20.0,2019-07-06,"February 7, 2019","Synth-Pop,Pop","Howard lawrence, Guy lawrence, Khalid",Talk \nCan we just talk? Can we just talk?\nTa...,NaN
4,5,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"May 10, 2019","Canada,UK,Dance,Dance-Pop,Pop","Ed sheeran, Justin bieber, Shellback, Max mart...",I Don't Care \nI'm at a party I don't wanna be...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
97220,97221,Vitamin C,Smile,95,NaN,NaN,1999-07-12,NaN,"Jamaica,Pop","Colleen fitzpatrick, Josh deutsch","Smile \nHahaha\nAlright, yeah\nAlright\nFirst ...",Lady Saw
97221,97222,Collective Soul,Heavy,96,73.0,20.0,1999-07-12,NaN,"Hockey,Gaming,Soundtrack,Rock",Collective soul,Heavy \nComplicate this world you wrapped for ...,NaN
97222,97223,Mary Chapin Carpenter,Almost Home,97,NaN,NaN,1999-07-12,NaN,"Country,Pop","Annie roboff, Beth nielsen chapman, Mary chapi...",Almost Home \nI saw my life this morning\nLyin...,NaN
97223,97224,Q,Vivrant Thing,98,NaN,NaN,1999-07-12,NaN,Rap,"Q tip, J dilla, Barry white",Vivrant Thing \nUh check it out now\nUh no dou...,NaN
97224,97225,The Offspring,Why Don't You Get A Job?,100,74.0,15.0,1999-07-12,NaN,"Ska,Punk Rock,Rock",Dexter holland,Why Don't You Get a Job? \nMy friend's got a g...,NaN

 # Transform DATA
 I begin to look over and change the data into a format more useful for our project.

In [3]:
#Checking the Week type
billboard_data_df['Week']

0        2019-07-06
1        2019-07-06
2        2019-07-06
3        2019-07-06
4        2019-07-06
            ...
97220    1999-07-12
97221    1999-07-12
97222    1999-07-12
97223    1999-07-12
97224    1999-07-12
Name: Week, Length: 97225, dtype: object

In [4]:
# Changing it from an object to a Date
billboard_data_df['Week'] = pd.to_datetime(billboard_data_df['Week'], errors='coerce')

In [5]:
billboard_data_df['Week']

0       2019-07-06
1       2019-07-06
2       2019-07-06
3       2019-07-06
4       2019-07-06
           ...
97220   1999-07-12
97221   1999-07-12
97222   1999-07-12
97223   1999-07-12
97224   1999-07-12
Name: Week, Length: 97225, dtype: datetime64[ns]

In [6]:
billboard_data_df['Week'].dt.year >= 2010

0         True
1         True
2         True
3         True
4         True
         ...
97220    False
97221    False
97222    False
97223    False
97224    False
Name: Week, Length: 97225, dtype: bool

In [7]:
billboard_years = billboard_data_df['Week'].dt.year >= 2010

In [8]:
billboard_years

0         True
1         True
2         True
3         True
4         True
         ...
97220    False
97221    False
97222    False
97223    False
97224    False
Name: Week, Length: 97225, dtype: bool

In [9]:
# Changed the data to only show specific years
billboard_09to19_df = billboard_data_df[(billboard_data_df['Week'].dt.year >= 2009)]

In [10]:
billboard_09to19_df.head()

,Unnamed: 0,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Date,Genre,Writing.Credits,Lyrics,Features
0,1,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr...","Jozzy, Atticus ross, Trent reznor, Billy ray c...","Old Town Road Remix \nOh, oh-oh\nOh\nYeah, I'm...",Billy Ray Cyrus
1,2,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,NaN,2019-07-06,"June 21, 2019",Pop,"Cashmere cat, Jack patterson, Charli xcx, Benn...",Senorita \nI love it when you call me senorita...,NaN
2,3,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ...","Billie eilish, Finneas","bad guy \nWhite shirt now red, my bloody nose\...",NaN
3,4,Khalid,Talk,4,3.0,20.0,2019-07-06,"February 7, 2019","Synth-Pop,Pop","Howard lawrence, Guy lawrence, Khalid",Talk \nCan we just talk? Can we just talk?\nTa...,NaN
4,5,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"May 10, 2019","Canada,UK,Dance,Dance-Pop,Pop","Ed sheeran, Justin bieber, Shellback, Max mart...",I Don't Care \nI'm at a party I don't wanna be...,NaN

In [11]:
#started to clean it up more and dropped unused columns
cleaned_billboard_09to19 = billboard_09to19_df.drop(columns=['Unnamed: 0', 'Writing.Credits', 'Lyrics', 'Features'])

In [12]:
#billboard_09to19_df.to_csv("Resources/billboardHot100_2009-2019.csv", index=False, header=True)

In [13]:
cleaned_billboard_09to19.head(102)

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Date,Genre
0,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr..."
1,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,NaN,2019-07-06,"June 21, 2019",Pop
2,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ..."
3,Khalid,Talk,4,3.0,20.0,2019-07-06,"February 7, 2019","Synth-Pop,Pop"
4,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"May 10, 2019","Canada,UK,Dance,Dance-Pop,Pop"
...,...,...,...,...,...,...,...,...
97,Drake,Omerta,99,35.0,2.0,2019-07-06,"June 15, 2019","Hip-Hop,Basketball,NBA,Canada,Rap"
98,Martin Garrix,Summer Days,100,NaN,NaN,2019-07-06,"April 25, 2019","Electronic Pop,Electro,Electro House,Nederland..."
99,"Lil Nas,",Old Town Road,1,1.0,6.0,2019-06-29,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr..."
100,Taylor Swift,You Need To Calm Down,2,NaN,NaN,2019-06-29,"June 14, 2019","Synth-Pop,LGBTQ+,Pop"
101,Billie Eilish,Bad Guy,3,2.0,12.0,2019-06-29,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ..."

### Name changes
The following lines are used to change the names of a couple of columns to use for the SQL table. Also to change a particular song and artist that was put in with the wrong information.

In [38]:
cleaned_billboard_09to19 = cleaned_billboard_09to19.rename(columns = {"Name":"Song_Title"})

In [39]:
cleaned_billboard_09to19 = cleaned_billboard_09to19.rename(columns = {"Weekly.rank":"Weekly_rank"})

In [40]:
cleaned_billboard_09to19 = cleaned_billboard_09to19.rename(columns = {"Peak.position":"Peak_posistion"})

In [41]:
cleaned_billboard_09to19 = cleaned_billboard_09to19.rename(columns = {"Weeks.on.chart":"Weeks_on_chart"})

Below are lines of code to change a couple of things of a certain title that was in with the wrong names. Was able to find them in the data then change it to the actual title.

In [42]:
#Changing certain problem in the data
cleaned_billboard_09to19 = cleaned_billboard_09to19.replace({'Song_Title': r'^1'}, {'Song_Title': '1-800-273-8255'}, regex=True)

In [43]:
cleaned_billboard_09to19 = cleaned_billboard_09to19.replace({'Artists': r'^800'}, {'Artists': 'Logic'}, regex=True)

In [44]:
cleaned_billboard_09to19.loc[cleaned_billboard_09to19['Song_Title']=='1-800-273-8255']

Empty DataFrame
Columns: [Artists, Song_Title, Weekly_rank, Peak_posistion, Weeks_on_chart, Week, Date, Genre]
Index: []

In [45]:
cleaned_billboard_09to19

,Artists,Song_Title,Weekly_rank,Peak_posistion,Weeks_on_chart,Week,Date,Genre
0,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr..."
1,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,NaN,2019-07-06,"June 21, 2019",Pop
2,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ..."
3,Khalid,Talk,4,3.0,20.0,2019-07-06,"February 7, 2019","Synth-Pop,Pop"
4,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"May 10, 2019","Canada,UK,Dance,Dance-Pop,Pop"
...,...,...,...,...,...,...,...,...
51875,Beyonce,Diva,96,NaN,NaN,2009-01-01,"January 20, 2009","Rap,R&;B,Pop"
51876,Bobby V,Beep,97,NaN,NaN,2009-01-01,"October 27, 2008","R&;B,Pop"
51877,Randy Houser,Anything Goes,98,92.0,5.0,2009-01-01,"June 2, 2008",Country
51878,The,Rockin' That Thang,99,NaN,NaN,2009-01-01,"December 9, 2008",R&;B
51879,Darius Rucker,It Won't Be Like This For Long,100,NaN,NaN,2009-01-01,NaN,"Country,Rock"

In [46]:
# Saved the new dataframe into a CSV file
cleaned_billboard_09to19.to_csv("Resources/cleaned_billboardHot100_2009-2019.csv", index=False, header=True)

# Loading the Data into SQL
The table for the data has been set up in pgAdmin in a database called "music_DB" with a table called billboard.

In [47]:
# Connect to the datbase
rds_connection_string = key
engine = create_engine(f'postgresql://{rds_connection_string}')

In [48]:
# Check to see Table name
engine.table_names()

['billboard']

In [51]:
# Add the data to the database
cleaned_billboard_09to19.to_sql('billboard', engine, if_exists='replace', index=False)

In [ ]:
# Load dataframe as table to Postgres, using connection from above
clean_grammy_df.to_sql('grammys', engine, if_exists='replace',index=False) #drops old table and creates new empty table